spring:
  profiles:
    #环境 开发dev，测试test，生产prod
    active:
  #jackson
  jackson:
    #驼峰转下划线
    property-naming-strategy: SNAKE_CASE
    #时间格式
    time-zone: GMT+8
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    #不为空的属性才会序列化
    default-property-inclusion: NON_NULL
    #序列化设置
    serialization:
      write-dates-as-timestamps: true
      fail-on-empty-beans: true
    #反序列化设置
    deserialization:
      fail-on-unknow-properties: true
    #servlet
    servlet:
      multipart:
        #文件上传大小配置
        max-file-size: 100MB
        max-request-size: 100MB
    #mvc
    mvc:
      #restFul风格：当找不到页面时，正常抛出错误，不跳转页面
      throw-exception-if-no-handler-found: true
      #仅映射static资源文件
      static-path-pattern: /static/**
    #resources
    resources:
      #restFul风格: 不要为资源文件建立映射
      add-mappings: false
#tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    connection-timeout: 5000ms
  #端口配置
  port: 80
  servlet:
    #映射项目路径
    context-path: /
#log
logging:
  config: log4j2.xml
